"""The CLI driver — the workflow core's first (and currently only) frontend.

Docs: https://cj-mills.github.io/cjm-transcription-corecli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/cli.ipynb.

# %% auto #0
__all__ = ['logger', 'build_parser', 'parse_max_concurrent', 'load_capabilities', 'run_command', 'main']

# %% ../nbs/cli.ipynb #5f7a1ed8
import argparse
import asyncio
import getpass
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from cjm_substrate.core.manager import CapabilityManager
from cjm_substrate.core.queue import JobQueue

from .models import PipelineConfig
from .pipeline import run_pipeline

logger = logging.getLogger(__name__)

# %% ../nbs/cli.ipynb #ca818ebc
def build_parser() -> argparse.ArgumentParser:  # Configured CLI parser
    """Build the CLI parser (subcommands: run)."""
    parser = argparse.ArgumentParser(
        prog="cjm-transcription-core",
        description="Headless transcription pipeline: VAD -> segment -> convert -> transcribe [-> graph emission].",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    run = sub.add_parser("run", help="Run the pipeline over one or more audio files")
    run.add_argument("audio", nargs="+", help="Source audio file path(s), in order")
    run.add_argument("--manifests-dir", default=".cjm/manifests", help="Capability manifests directory")
    run.add_argument("--transcriber", action="append", default=None,
                     help="Transcription capability name; REPEATABLE for the dual-transcriber "
                          "(lightweight + accuracy) comparison run (default: cjm-capability-whisper)")
    run.add_argument("--vad-plugin", default="cjm-capability-silero-vad", help="VAD capability name")
    run.add_argument("--ffmpeg-plugin", default="cjm-capability-ffmpeg", help="Convert/segment capability name")
    run.add_argument("--preprocessing-plugin", default=None,
                     help="Opt-in audio-preprocessing capability (e.g. cjm-capability-demucs for vocals "
                          "isolation); runs per-segment on FULL-BAND audio BEFORE the model-input convert, "
                          "via the source_separation task channel (default: no preprocessing)")
    run.add_argument("--graph-plugin", default=None,
                     help="Graph-storage capability for Source/AudioSegment/Transcript emission "
                          "(CR-18 revolution 2); default: no emission, manifest-only run")
    run.add_argument("--graph-db-path", default=None,
                     help="Explicit graph DB path override (caller-wins config, C8/F10; default: the capability's configured db_path)")
    run.add_argument("--sysmon-plugin", default=None, help="MonitorPlugin capability for GPU subtree attribution (CR-7); loaded first; default: no monitor")
    run.add_argument("--max-concurrent", action="append", default=None, metavar="NAME=N",
                     help="Per-capability SG-33 max_concurrent_requests override, REPEATABLE "
                          "(e.g. --max-concurrent cjm-capability-ffmpeg=4); same-worker "
                          "concurrency is opt-in — subprocess-backed workers parallelize, "
                          "model workers stay serial-per-instance (default: unset = 1)")
    run.add_argument("--max-segment-duration", type=float, default=220.0, help="Wall-clock cap per segment in seconds (220 keeps each forced-alignment input clear of the qwen3-FA ~240-250s degeneracy cliff; FA over-assignment investigation 2026-06-16)")
    run.add_argument("--sample-rate", type=int, default=16000, help="Model-input sample rate")
    run.add_argument("--channels", type=int, default=1, help="Model-input channel count")
    run.add_argument("--force", action="store_true", help="Bypass capability-side caches (VAD + transcription + preprocessing)")
    run.add_argument("-y", "--yes", action="store_true", help="Auto-accept HITL seams (headless mode)")
    run.add_argument("--output", default=None, help="Run-manifest output path (default: runs/<run_id>.json)")
    run.add_argument("--actor", default=None,
                     help="Journal attribution for who/what initiated this run (default: cli:<username>)")
    run.add_argument("-v", "--verbose", action="store_true", help="DEBUG-level logging")
    return parser

# %% ../nbs/cli.ipynb #61825613
def parse_max_concurrent(
    values: Optional[List[str]],  # Repeatable NAME=N CLI values (None = no overrides)
) -> Dict[str, int]:  # Capability name -> SG-33 max_concurrent_requests
    """Parse repeatable `--max-concurrent NAME=N` values into a per-capability cap map."""
    out: Dict[str, int] = {}
    for v in values or []:
        name, sep, n = v.partition("=")
        if not sep or not name:
            raise SystemExit(f"--max-concurrent expects NAME=N, got {v!r}")
        try:
            cap = int(n)
        except ValueError:
            raise SystemExit(f"--max-concurrent expects an integer cap, got {v!r}")
        if cap < 1:
            raise SystemExit(f"--max-concurrent cap must be >= 1, got {v!r}")
        out[name] = cap
    return out

# %% ../nbs/cli.ipynb #f0de5ec6
def load_capabilities(
    manager: CapabilityManager,   # Freshly constructed manager
    instance_ids: List[str],  # Capability names to load (default instances)
    configs: Optional[Dict[str, Dict[str, Any]]] = None,  # Per-capability config overrides (caller-wins, C8)
    max_concurrent: Optional[Dict[str, int]] = None,  # Per-capability SG-33 max_concurrent_requests (unset = queue default of 1)
) -> None:
    """Discover manifests + load each requested capability (default instance)."""
    manager.discover_manifests()
    discovered = {m.name: m for m in manager.discovered}
    for iid in instance_ids:
        meta = discovered.get(iid)
        if meta is None:
            raise SystemExit(
                f"capability {iid!r} not found in manifests "
                f"(discovered: {sorted(discovered)}) — run cjm-ctl install-all first"
            )
        if not manager.load_capability(meta, config=(configs or {}).get(iid),
                                   max_concurrent_requests=(max_concurrent or {}).get(iid)):
            raise SystemExit(f"failed to load capability {iid!r}")
        logger.info(f"loaded {iid}")

# %% ../nbs/cli.ipynb #371d5ac1
async def run_command(
    args: argparse.Namespace,  # Parsed CLI arguments for the `run` subcommand
) -> int:  # Process exit code (0 = all sources completed)
    """Execute the `run` subcommand: full pipeline over the given audio files."""
    transcribers = list(args.transcriber or ["cjm-capability-whisper"])
    cfg = PipelineConfig(
        vad_plugin=args.vad_plugin,
        ffmpeg_plugin=args.ffmpeg_plugin,
        transcriber_plugins=transcribers,
        preprocessing_plugin=args.preprocessing_plugin,
        graph_plugin=args.graph_plugin,
        graph_db_path=args.graph_db_path,
        max_segment_duration=args.max_segment_duration,
        sample_rate=args.sample_rate,
        channels=args.channels,
        force=args.force,
        assume_yes=args.yes,
    )
    sources = [str(Path(p).resolve()) for p in args.audio]
    missing = [s for s in sources if not Path(s).exists()]
    if missing:
        raise SystemExit(f"missing audio file(s): {missing}")
    if args.graph_db_path and not args.graph_plugin:
        raise SystemExit("--graph-db-path requires --graph-plugin")
    max_concurrent = parse_max_concurrent(args.max_concurrent)

    # CR-7 GPU subtree attribution is opt-in: --sysmon-plugin threads the monitor
    # name into BOTH the manager (load-time empirical records) and the queue
    # (per-job resource samples); the monitor loads FIRST so GPU capabilities'
    # samples record gpu_memory_mb_peak (voxtral-vllm e2e pattern).
    manager = CapabilityManager(
        search_paths=[Path(args.manifests_dir)],
        sysmon_capability_name=args.sysmon_plugin,
    )
    # Preprocessing (opt-in) loads alongside the other compute capabilities; its
    # adapter auto-binds by surface match exactly like VAD/transcription.
    instance_ids = ([cfg.ffmpeg_plugin, cfg.vad_plugin]
                    + ([cfg.preprocessing_plugin] if cfg.preprocessing_plugin else [])
                    + list(cfg.transcriber_plugins)
                    + ([cfg.graph_plugin] if cfg.graph_plugin else []))
    load_order = ([args.sysmon_plugin] if args.sysmon_plugin else []) + instance_ids
    # --graph-db-path threads a caller-wins config into the graph load (C8/F10).
    configs = ({cfg.graph_plugin: {"db_path": args.graph_db_path}}
               if (cfg.graph_plugin and args.graph_db_path) else None)
    load_capabilities(manager, load_order, configs=configs, max_concurrent=max_concurrent)

    queue = JobQueue(deps=manager, sysmon_capability_name=args.sysmon_plugin)
    await queue.start()
    try:
        # CR-14 follow-up: actor attribution (operator identity by default;
        # agents/services pass --actor explicitly).
        actor = args.actor or f"cli:{getpass.getuser()}"
        manifest = await run_pipeline(manager, queue, cfg, sources, actor=actor)
    finally:
        await queue.stop()
        for iid in reversed(load_order):  # Reverse load order; the monitor unloads last
            try:
                manager.unload_capability(iid)
            except Exception as e:  # Best-effort teardown; never mask the run's outcome
                logger.warning(f"unload {iid} failed: {e}")

    out = Path(args.output) if args.output else Path("runs") / f"{manifest.run_id}.json"
    manifest.save(out)
    done = sum(len(s.segments) for s in manifest.sources)
    print(f"run manifest: {out}")
    print(f"sources completed: {len(manifest.sources)}/{len(sources)}  segments: {done}  transcribers: {len(transcribers)}")
    if cfg.preprocessing_plugin:
        print(f"preprocessing: {cfg.preprocessing_plugin} ({cfg.preprocessing_task}/{cfg.preprocessing_method})")
    if cfg.graph_plugin:
        for s in manifest.sources:
            print(f"graph emission [{Path(s.source_path).name}]: {s.graph}")
    return 0 if len(manifest.sources) == len(sources) else 1

# %% ../nbs/cli.ipynb #feae285d
def main(
    argv: Optional[List[str]] = None,  # Argument list override (None = sys.argv)
) -> int:  # Process exit code
    """CLI entry point (console script: `cjm-transcription-core`)."""
    args = build_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s :: %(message)s",
    )
    if args.command == "run":
        return asyncio.run(run_command(args))
    raise SystemExit(f"unknown command: {args.command}")
