"""Fill in a module description here

Docs: https://cj-mills.github.io/cjm-transcription-corecore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #4bfc6a0d
def foo(): pass
