"""Graph-root emission (CR-18 revolution 2): a completed source EMITS `Source -> AudioSegment -> Transcript` into the shared context graph — the graph now BEGINS at transcription (where-graph-begins resolution: ingestion is the first EXTENDER that plants the root). Deterministic identity tuples make emission idempotent: re-runs (cache hits included) collide into verified no-ops instead of duplicating roots (the E13 hazard, relocated into graph creation and discharged).

Docs: https://cj-mills.github.io/cjm-transcription-coreemission.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/emission.ipynb.

# %% auto #0
__all__ = ['logger', 'build_source_emission', 'emit_source_graph']

# %% ../nbs/emission.ipynb #4905e128
import logging
from typing import Any, Dict, List, Tuple

from cjm_plugin_system.core.queue import JobQueue
from cjm_context_graph_layer.grammar import spine_edges
from cjm_context_graph_layer.ops import extend_graph
from cjm_context_graph_layer.declare import Derivation, derivation_to_graph
from cjm_transcript_graph_schema.schema import SourceNode, AudioSegmentNode, TranscriptNode

from .models import SourceResult

logger = logging.getLogger(__name__)

# %% ../nbs/emission.ipynb #fbacb912
def build_source_emission(
    src: SourceResult,                          # Completed per-source pipeline result (0.2.0 shape)
    transcriber_config_hashes: Dict[str, str],  # transcriber -> effective config hash (Transcript identity input)
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Any]]:  # (nodes, edges, ids)
    """Build the graph-root payload for one source (pure; no capability calls).

    Emits the locked layer schema: one `Source` (identity = file content hash)
    -> coarse `AudioSegment` spine (PART_OF / NEXT / STARTS_WITH via
    `spine_edges`) -> per-transcriber `Transcript` variants (DERIVED_FROM their
    AudioSegment; identity mirrors the capability cache key). Returns the ids
    dict {"source", "audio_segments", "transcripts"} for callers (decomp
    recomputes these same ids from the manifest — no stored-id coupling).
    """
    if not src.content_hash:
        raise ValueError(f"source {src.source_path} has no content_hash — emission identity requires it")
    source = SourceNode(content_hash=src.content_hash, path=src.source_path)
    nodes: List[Dict[str, Any]] = [source.to_graph_node()]
    edges: List[Dict[str, Any]] = []
    aseg_ids: List[str] = []
    transcript_ids: Dict[str, List[str]] = {}

    for rec in src.segments:
        if not rec.model_input_hash:
            raise ValueError(f"segment {rec.index} has no model_input_hash — emission identity requires it")
        aseg = AudioSegmentNode(
            source=source.id, index=rec.index, start=rec.start, end=rec.end,
            model_input_path=rec.model_input_path, model_input_hash=rec.model_input_hash,
            segment_path=rec.segment_path,
        )
        nodes.append(aseg.to_graph_node())
        aseg_ids.append(aseg.id)
        for tname, tr in rec.transcripts.items():
            tnode = TranscriptNode(
                audio_segment=aseg.id, transcriber=tname,
                config_hash=transcriber_config_hashes.get(tname, ""),
                text=str(tr.get("text") or ""), audio_hash=rec.model_input_hash,
                metadata=dict(tr.get("metadata") or {}),
            )
            nodes.append(tnode.to_graph_node())
            edges.append(tnode.derived_edge())
            transcript_ids.setdefault(tname, []).append(tnode.id)

    edges = spine_edges(source.id, aseg_ids) + edges
    ids = {"source": source.id, "audio_segments": aseg_ids, "transcripts": transcript_ids}
    return nodes, edges, ids

# %% ../nbs/emission.ipynb #7a2d6cab
async def emit_source_graph(
    queue: JobQueue,                            # Started job queue
    graph_id: str,                              # Graph-storage capability instance id
    src: SourceResult,                          # Completed per-source pipeline result
    transcriber_config_hashes: Dict[str, str],  # transcriber -> effective config hash
    run_id: str,                                # Run id (recorded on the boundary Derivation event)
) -> Dict[str, Any]:  # Emission record for the manifest
    """Idempotently emit one source's graph root through the task channel.

    `extend_graph` = emit-if-absent + verify-if-present, so a re-run over
    cached content collides into a verified no-op (stress item 4) and a second
    transcriber's run EXTENDS the existing root (only its Transcript nodes are
    new). The host's boundary computation is declared as a `Derivation` event
    (provenance-by-declaration) ONLY when this run actually created
    AudioSegment nodes — verified re-emissions don't spam the audit trail.
    """
    nodes, edges, ids = build_source_emission(src, transcriber_config_hashes)
    res = await extend_graph(queue, graph_id, nodes, edges)
    newly_created_asegs = set(ids["audio_segments"]) & set(res.added_node_ids)
    if newly_created_asegs:
        d = Derivation(
            actor="host:cjm-transcription-core", method="segment-boundaries/v1",
            input_ids=[ids["source"]], output_ids=list(ids["audio_segments"]),
            properties={"run_id": run_id},
        )
        dn, de = derivation_to_graph(d)
        await extend_graph(queue, graph_id, [dn], de)
    record = {
        "source_node_id": ids["source"],
        "nodes_added": res.nodes_added,
        "nodes_verified": res.nodes_verified,
        "edges_added": res.edges_added,
        "edges_existing": res.edges_existing,
    }
    logger.info(f"emitted {src.source_path}: {record}")
    return record
