"""Data shapes for the transcription pipeline: run configuration + the run-manifest result containers.

Docs: https://cj-mills.github.io/cjm-transcription-coremodels.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['PipelineConfig', 'SegmentRecord', 'SourceResult', 'RunManifest', 'new_run_id']

# %% ../nbs/models.ipynb #132bf774
import json
import time
import uuid
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

# %% ../nbs/models.ipynb #f9cfb13b
@dataclass
class PipelineConfig:
    """Configuration for one transcription pipeline run."""
    vad_plugin: str = "cjm-media-plugin-silero-vad"               # VAD capability instance id
    ffmpeg_plugin: str = "cjm-media-plugin-ffmpeg"                # Convert/segment capability instance id
    transcriber_plugins: List[str] = field(                       # Transcription capability instance ids (one or more; stage-5 dual-transcriber)
        default_factory=lambda: ["cjm-transcription-plugin-whisper"])
    graph_plugin: Optional[str] = None   # Graph-storage capability for Source/AudioSegment/Transcript emission (None = no emission)
    graph_db_path: Optional[str] = None  # Explicit graph DB path override (caller-wins config, C8/F10)
    max_segment_duration: float = 300.0  # Wall-clock cap per segment in seconds (pre-emptive cuts)
    sample_rate: int = 16000             # Model-input sample rate for the per-segment convert step
    channels: int = 1                    # Model-input channel count
    force: bool = False                  # Bypass capability-side caches (VAD + transcription)
    assume_yes: bool = False             # Auto-accept HITL seams (headless / corpus-generation mode)

    def to_dict(self) -> Dict[str, Any]:  # Plain-dict snapshot for the run manifest
        """Serialize to a plain dict."""
        return asdict(self)

# %% ../nbs/models.ipynb #7baa6c96
@dataclass
class SegmentRecord:
    """One segment of a source audio file, with per-transcriber transcripts.

    Manifest schema 0.2.0: the single text/job_id pair became `transcripts`
    keyed by transcriber capability name — transcription emits SYMMETRIC
    variants; the authority designation is the decomp consumer's choice
    (stage-5 ratified design). `model_input_hash` content-addresses the
    model-input WAV (the audio of record, E14) for graph emission identity."""
    index: int              # 0-based position within the source
    start: float            # Segment start in source-audio seconds
    end: float              # Segment end in source-audio seconds
    duration: float         # Wall-clock segment duration in seconds
    segment_path: str       # Cut audio file (source codec) from ffmpeg `segment_audio`
    model_input_path: str   # Model-ready WAV from the per-segment `convert` step
    model_input_hash: str = ""  # Content hash over the model-input WAV ("algo:hexdigest")
    transcripts: Dict[str, Dict[str, Any]] = field(default_factory=dict)  # transcriber -> {job_id, text, metadata}

    def to_dict(self) -> Dict[str, Any]:  # Plain-dict form for the run manifest
        """Serialize to a plain dict."""
        return asdict(self)

# %% ../nbs/models.ipynb #b8806ed1
@dataclass
class SourceResult:
    """Pipeline result for one source audio file."""
    source_path: str        # Original input audio path
    duration: float         # Source duration in seconds
    vad_chunk_count: int    # Number of speech chunks VAD detected
    batch_key: str          # ffmpeg `segment_audio` batch key linking the cut files
    content_hash: str = ""  # Content hash over the source file (Source node identity input)
    segments: List[SegmentRecord] = field(default_factory=list)  # Ordered transcribed segments
    graph: Optional[Dict[str, Any]] = None  # Emission record: {source_node_id, nodes_added, nodes_verified, edges_added} (None = not emitted)

    def to_dict(self) -> Dict[str, Any]:  # Plain-dict form for the run manifest
        """Serialize to a plain dict with nested segments."""
        return {
            "source_path": self.source_path,
            "duration": self.duration,
            "vad_chunk_count": self.vad_chunk_count,
            "batch_key": self.batch_key,
            "content_hash": self.content_hash,
            "segments": [s.to_dict() for s in self.segments],
            "graph": self.graph,
        }

# %% ../nbs/models.ipynb #10fbe0e4
@dataclass
class RunManifest:
    """Durable record of one pipeline run (proto-bundle; see CR-20).

    Schema 0.2.0 (stage 5): per-segment `transcripts` keyed by transcriber +
    source `content_hash` + per-segment `model_input_hash` + plugin
    `config_hash` — everything a downstream extender needs to RECOMPUTE the
    deterministic graph node ids (no search, no stored-id coupling)."""
    run_id: str                       # Unique run identifier
    created_at: float                 # Unix timestamp at run start
    config: Dict[str, Any]            # PipelineConfig snapshot
    plugins: Dict[str, Dict[str, Any]] = field(default_factory=dict)  # instance_id -> {name, version, db_path, config_hash}
    sources: List[SourceResult] = field(default_factory=list)         # Per-source results, input order
    graph: Optional[Dict[str, Any]] = None  # Emission target: {plugin, db_path} (None = no emission this run)

    FORMAT: str = field(default="cjm-transcription-core/run-manifest", repr=False)  # Manifest format tag
    VERSION: str = field(default="0.2.1", repr=False)                               # Manifest schema version

    def to_dict(self) -> Dict[str, Any]:  # Plain-dict form for JSON serialization
        """Serialize to a plain dict with nested sources."""
        return {
            "format": self.FORMAT,
            "version": self.VERSION,
            "run_id": self.run_id,
            "created_at": self.created_at,
            "config": self.config,
            "plugins": self.plugins,
            "sources": [s.to_dict() for s in self.sources],
            "graph": self.graph,
        }

    def save(
        self,
        path: Union[str, Path],  # Destination JSON file (parent dirs created)
    ) -> Path:  # The written path
        """Write the manifest as pretty-printed JSON."""
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(self.to_dict(), indent=2))
        return out

# %% ../nbs/models.ipynb #7bebc32a
def new_run_id() -> str:  # e.g. "run_20260607_153000_1a2b3c4d"
    """Generate a unique, sortable run id."""
    return f"run_{time.strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:8]}"
